# Generated by Django 5.1.1 on 2024-10-01 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'CompanyApp',
            },
        ),
        migrations.CreateModel(
            name='Personalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('info', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.TextField()),
                ('image', models.TextField()),
            ],
            options={
                'db_table': 'Personalities',
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolya', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.companyapp')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.personalities')),
            ],
            options={
                'db_table': 'CompanyUser',
            },
        ),
    ]
