# Generated by Django 5.1.1 on 2024-10-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalities',
            name='number',
            field=models.TextField(blank=True),
        ),
    ]
