# Generated by Django 5.1.1 on 2024-10-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_alter_personalities_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='dolya',
            field=models.TextField(blank=True),
        ),
    ]
