# Generated by Django 5.1.1 on 2024-10-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0003_alter_companyuser_dolya'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyapp',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
