# Generated by Django 5.1.1 on 2024-10-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0004_companyapp_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Application',
            },
        ),
        migrations.RenameModel(
            old_name='CompanyApp',
            new_name='Company',
        ),
    ]
