# Generated by Django 5.1.1 on 2024-10-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0005_application_rename_companyapp_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
