# Generated by Django 5.1.1 on 2024-10-01 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0006_delete_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.company')),
            ],
            options={
                'db_table': 'Application',
            },
        ),
    ]
